# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 14:58
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_config', '0005_auto_20180719_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedCourseVideos',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('edx_video_id', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code=b'invalid edx_video_id', message=b'edx_video_id has invalid characters', regex=b'^[a-zA-Z0-9\\-_]*$')])),
                ('command_run', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoThumbnailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('command_run', models.PositiveIntegerField(default=0)),
                ('batch_size', models.PositiveIntegerField(default=0)),
                ('commit', models.BooleanField(default=False, help_text=b'Dry-run or commit.')),
                ('all_course_videos', models.BooleanField(default=False, help_text=b'Process all videos.')),
                ('course_ids', models.TextField(help_text=b'Whitespace-separated list of course ids for which to update videos.')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
    ]
